<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN511297" failures="1" tests="4" name="Regression Test" time="101.789" errors="0" timestamp="2024-11-02T10:03:21 IST">
  <testcase classname="testCases.TC_004_Cousera" name="openCousera" time="0.075"/>
  <testcase classname="testCases.TC_001_SearchForWebDevelopmentCourses" name="SearchForWebDevelopmentCourses" time="24.245"/>
  <testcase classname="testCases.TC_002_Language_Learning" name="selectingLanguages" time="25.668">
    <failure type="java.lang.AssertionError" message="Test case failed due to an exception: Index 0 out of bounds for length 0">
      <![CDATA[java.lang.AssertionError: Test case failed due to an exception: Index 0 out of bounds for length 0
at testCases.TC_002_Language_Learning.selectingLanguages(TC_002_Language_Learning.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- selectingLanguages -->
  <testcase classname="testCases.TC_003_FormFilling" name="formFilling" time="8.966"/>
</testsuite> <!-- Regression Test -->
